package org.test.spark.remote
package remotetest

import org.apache.spark.sql.execution.streaming.FileStreamSource.Timestamp
import java.sql.Date

case class Medication(id: Option[Int],
                      administration: String = " ",
                      source: String = " ",
                      comments: String = " ",
                      din: String = " ",
                      dru_text: String = " ",
                      generic_name: String = " ",
                      trade_name: String = " ",
                      drug_form: String = " ",
                      strength: String = " ",
                      duration: String = " ",
                      dose: String = " ",
                      frequency: String = " ",
                      indication: String = " ",
                      exception_code: String = " ",
                      justification_code: String = " ",
                      issued_name: String = " ",
                      quantity: String = " ",
                      repetatur: String = " ",
                      start_date: Option[Timestamp],
                      end_date: Option[Timestamp],
                      removed_name: String = " ",
                      removed_reason: String = " ",
                      therapy_intention: String,
                      created: Option[Timestamp],
                      last_modified: Option[Timestamp],
                      antiretroviral_code: String = " ",
                      xref_patient: Option[Int],
                      patient_id: Option[Int])

case class Alert(id: Option[Int],
                 source: String,
                 event_type: String,
                 bones_event_type: String,
                 event_category: Option[Int],
                 targetted_medication: String,
                 status: String,
                 status_last_modified: Option[Timestamp],
                 note: String,
                 created: Option[Timestamp],
                 last_modified: Option[Timestamp],
                 due_date: Option[Date],
                 end_date: Option[Timestamp],
                 recall_date: Option[Date],
                 test_date: Option[Timestamp],
                 treatment_date: Option[Timestamp],
                 priority: Option[Int],
                 xref_patient: Option[Int],
                 patient_id: Option[Int])

case class Allergy(
                    id: Option[Int],
                    created: Option[Timestamp],
                    last_modified: Option[Timestamp],
                    source: String,
                    allergen: String,
                    reaction: String,
                    desenstization_date: Option[Timestamp],
                    sub_type: Option[Int],
                    code: Option[Int],
                    din: Option[Int],
                    drawing_document: Option[Array[Byte]],
                    start_date: Option[Timestamp],
                    end_date: Option[Timestamp],
                    note: String,
                    xref_patient: Option[Int],
                    patient_id: Option[Int])

case class Patient(id: Option[Int],
                   born_date: Option[Timestamp],
                   created: Option[Timestamp],
                   last_modified: Option[Timestamp],
                   gender: String,
                   gender_other: String,
                   last_annual_examination: Option[Timestamp],
                   last_consultation: Option[Timestamp],
                   doctor: String,
                   status: Option[Int], // was Short
                   born_city: String,
                   city: String,
                   country: String,
                   culture: String,
                   ethnical_origin: String,
                   marital_status: Option[Int], // was Short
                   nationality: Option[Int],    // was Short
                   occupation: String,
                   state: String,
                   zip: String,
                   sexual_orientation: String,
                   deceased_date: Option[Date],
                   born_country: String,
                   xref_patient: Option[Int])

case class FinalResult(id: Option[Int],
                       born_date: Option[Timestamp],
                       created: Option[Timestamp],
                       last_modified: Option[Timestamp],
                       gender: String,
                       gender_other: String,
                       last_annual_examination: Option[Timestamp],
                       last_consultation: Option[Timestamp],
                       doctor: String,
                       status: Option[Int], // was Short
                       born_city: String,
                       city: String,
                       country: String,
                       culture: String,
                       ethnical_origin: String,
                       marital_status: Option[Int], // was Short
                       nationality: Option[Int],    // was Short
                       occupation: String,
                       state: String,
                       zip: String,
                       sexual_orientation: String,
                       deceased_date: Option[Date],
                       born_country: String,
                       xref_patient: Option[Int],
                       medic_id: Option[Int],
                       medications: List[String],
                       alert_id: Option[Int],
                       alerts: List[String],
                       allergy_id: Option[Int],
                       allergies: List[String])
